# Generated by Django 5.0.14 on 2026-06-29 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.CharField(max_length=255, unique=True, verbose_name='Google Drive Folder ID')),
                ('name', models.CharField(max_length=255, verbose_name='Folder Name')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='movies.folder', verbose_name='Parent Folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True, verbose_name='Google Drive File ID')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display Title')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME Type')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='Size in Bytes')),
                ('thumbnail_link', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Thumbnail Link')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Last Synced At')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.folder', verbose_name='Containing Folder')),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
