# Generated by Django 5.0.14 on 2026-06-29 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster_link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Rich Cover Art Link'),
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('current_time_seconds', models.FloatField(default=0.0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('last_watched', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='movies.movie')),
            ],
            options={
                'ordering': ['-last_watched'],
                'unique_together': {('session_id', 'movie')},
            },
        ),
    ]
